### PR TITLE
Port to Python 3

### PR DESCRIPTION
**Pull request by Juanlu001**

### CODE REVIEW

**Comment by Juanlu001** [comment]
This is compatible with Python 2 and Python 3 at the same time, which I guess is closer to what you want.

**Comment by brianretford** [comment]
Hey @Juanlu001 , I added some basic CI tests and it looks like your PR breaks python 2.7, see the travis CI output. Can you get it to work with python 2.7 also? The python 3 part will hopefully go green once we push the plaidml python 3 pips (also working on that now)

**Comment by Juanlu001** [comment]
Sure, working on it.

**Comment by Juanlu001** [comment]
The package I was using to provide the compatibility layer was missing from `requirements.txt`. This should be ready now.

**Comment by brianretford** [comment]
Great! I'll merge this as soon as the python 3 pips are available.

**Comment by brianretford** [comment]
Thanks for all your help! I ended up porting to six and doing things a bit differently, but your commit officially turns of python 3 support.

**Comment by Juanlu001** [comment]
Awesome! :)

**Pull request merged**
